---
 - hosts: all/web1
   become: true
   gaher-facts: yes
   handlers:
    - name:restart
      service: 
        name: nginx
        state: restart
        
   tasks:
     - name: update servers
       shell: apt update
     - name: install nginx
       shell: apt install nginx -y or
       apt: name=nginx state=present
     - name:stop service
       service: name=nginx state=stopped enabled=no
     - notify: restart